test images: Updates echoserver to latest nginx
The image no longer builds for the s390x arch with the errors:

ERROR: Unable to open root: Bad address
ERROR: Failed to open apk database: Bad address
The command '/bin/sh -c apk add --no-cache openssl nginx-mod-http-lua
nginx-mod-http-lua-upstream' returned a non-zero code: 99
Makefile:37: recipe for target 'all-container' failed

Updates the BASEIMAGE nginx version to 1.17.4.
Adds bash in the image's Dockerfile, it is needed in order for the image
to be built.